# Generated by Django 4.0.3 on 2022-03-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='base_price',
        ),
        migrations.AddField(
            model_name='product',
            name='sale_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=3, null=True),
        ),
    ]
