# Generated by Django 4.0.3 on 2022-03-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category_delete_category'),
        ('shopping_cart', '0004_remove_cart_product_remove_cart_quantity_cart_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='CartItem',
        ),
    ]
