# Generated by Django 4.0.3 on 2022-03-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category_delete_category'),
        ('shopping_cart', '0008_alter_cartitem_cart_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.product', unique=True),
        ),
    ]
